### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by skys215** [codito/pyqtkeybind#2]
Hi, I'm trying to run this under macOS Sierra, but seems that I cant run.
I tried to upgrade both of `qt` and `pyqt`.
`No module named 'PyQt5.QtX11Extras'` error was reported.
I assumed that X11 is for linux, not sure that if Sierra supports it.
Did I do it wrong, or this package doesn't support macOS?

**Comment by codito** [comment]
@skys215 you're right x11 is for linux, this package won't work on macos (currently I don't have access to a macos box to fix this). Please let me know if you'd like to help add this support.

**Comment by skys215** [comment]
Since I haven't run this package yet, I wanna make something clear: is this package adding system-wide global shortcut/hotkey for pyqt programs? Or it's a package that adds program-wide shortcut to trigger something in the program?
I mean system-wide is like you can fire some event of the program even the program is minimized, like `Win+R` in Windows.
Program-wide shortcut is like the program is active/focused and pressing `Ctrl+Q` can close the window or whole program.
I'm just trying to clarify the definitions here to avoid ambiguity.

**Comment by codito** [comment]
It adds system-wide shortcuts.

**Comment by skys215** [comment]
Ok then, how should I help to test it on Mac?
