### ISSUE TITLE
Cannot re-register key after unbinding them

### ISSUE THREAD

**Issue by Cranbaerry** [codito/pyqtkeybind#3]
I found an issue that after you unregister a specific key, and try re-register them again, it wouldn't work. 
[Windows 10 Platform, Python 3.7]

**Comment by Cranbaerry** [comment]
Hello! Any updates on this?

**Comment by codito** [comment]
I haven't had the time to investigate this one yet.

**Comment by codito** [comment]
Fixed in https://pypi.org/project/pyqtkeybind/0.0.4/
