### ISSUE TITLE
unregister_hotkey on Linux

### ISSUE THREAD

**Issue by 2press** [codito/pyqtkeybind#5]
Is there are reason why `unregister_hotkey` is not implement for X11, yet:
https://github.com/codito/pyqtkeybind/blob/e6ae397522c453cdfe68e6cefc7049b3ed3e4af6/pyqtkeybind/x11/__init__.py#L32-L35

I am currently looking into using pyqtkeybind instead of the keyboard package. Having the `unregister_hotkey` functionality would be most welcome.

**Comment by codito** [comment]
@2press thanks for creating the issue. I will take a look.

**Comment by codito** [comment]
Fixed in https://pypi.org/project/pyqtkeybind/0.0.5/
