### ISSUE TITLE
Numerical shortcut?

### ISSUE THREAD

**Issue by Tomas1337** [codito/pyqtkeybind#9]
Hi there! Been checking out your library and it looks great.
Encountered this problem where I can't use a numerical key to the shortcut

```
        keybinder.register_hotkey(parent.winId(), 'Shift+Ctrl+A', self.callback) #WORKS
        keybinder.register_hotkey(parent.winId(), 'Shift+Ctrl+1', self.callback) #DOES NOT WORK

```
Would you have any suggestion on how to enable this?

**Comment by codito** [comment]
`Shift+Ctrl+1` is working for me (linux). Which environment are you on? Are you trying with `number keys` or `numeric keypad`?

**Comment by Tomas1337** [comment]
I'm on Windows 10.
Tried both with number keys and numeric key pad. Same result.

I've been somewhat investigating it.
Your library properly registers the keys to its `self.__keybind` dictionary when registering.

But it seems that the keybinder is not triggered when using that hotkey. Could it be a mismatch between what the OS sends and what is registered on the hotkey?

**Comment by Tomas1337** [comment]
Btw Function keys work no problem

**Comment by codito** [comment]
Please try `v0.0.7` https://pypi.org/project/pyqtkeybind/0.0.7/

**Comment by Tomas1337** [comment]
This works! Thanks!

**Comment by Tomas1337** [comment]
Btw, this new path broke the functionality of creating Function keys as hotkeys such as `Ctrl+Shift+F1`.

**Comment by codito** [comment]
@Tomas1337 ah, thanks, I see why this is breaking. Can you create a new issue? Will fix it in sometime.
